#!/usr/bin/env python3
"""
overlap_blockgroup_export.py — Reads overlap_results.json and exports
block group data as a JS file for embedding in the overlap dashboard.

Outputs: overlap_bg_data.js containing:
  - BG_OVERLAP: { "12-digit-geoid": { o, of, oh, a, b }, ... }
  - BG_BY_COUNTY: { "5-digit-county-fips": ["geoid1", "geoid2", ...], ... }
  - COUNTY_LOOKUP: { "5-digit-fips": { name, state, lat, lng }, ... }

Usage: python3 overlap_blockgroup_export.py
"""

import json
import os
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
INPUT_FILE = os.path.join(SCRIPT_DIR, 'overlap_results.json')
OUTPUT_FILE = os.path.join(SCRIPT_DIR, 'overlap_bg_data.js')


def main():
    if not os.path.exists(INPUT_FILE):
        print(f"[ERROR] {INPUT_FILE} not found. Run overlap_analysis.py first.")
        sys.exit(1)

    print(f"Reading {INPUT_FILE}...")
    with open(INPUT_FILE, 'r') as f:
        data = json.load(f)

    bg_data = data.get('by_block_group', {})
    if not bg_data:
        print("[ERROR] No by_block_group data found in results. Re-run overlap_analysis.py.")
        sys.exit(1)

    print(f"  {len(bg_data):,} block groups with overlap")

    # Build county index: county_fips -> [bg_geoid, ...]
    county_index = {}
    for bg_id in bg_data:
        county_fips = bg_id[:5]
        if county_fips not in county_index:
            county_index[county_fips] = []
        county_index[county_fips].append(bg_id)

    print(f"  {len(county_index):,} counties with overlap block groups")

    # Sort county index by total overlap (descending) for nice output
    county_overlap_totals = {}
    for county_fips, bg_ids in county_index.items():
        total = sum(bg_data[bg_id]['o'] for bg_id in bg_ids)
        county_overlap_totals[county_fips] = total

    # Write JS output
    print(f"Writing {OUTPUT_FILE}...")
    with open(OUTPUT_FILE, 'w') as f:
        f.write('// Auto-generated by overlap_blockgroup_export.py\n')
        f.write(f'// {len(bg_data):,} block groups with overlap across {len(county_index):,} counties\n\n')

        # BG_OVERLAP — flat object, compact keys
        f.write('const BG_OVERLAP = {\n')
        for i, (bg_id, stats) in enumerate(bg_data.items()):
            comma = ',' if i < len(bg_data) - 1 else ''
            f.write(f'"{bg_id}":{{o:{stats["o"]},of:{stats["of"]},oh:{stats["oh"]},a:{stats["a"]},b:{stats["b"]}}}{comma}\n')
        f.write('};\n\n')

        # BG_BY_COUNTY — county_fips -> [geoid, ...]
        f.write('const BG_BY_COUNTY = {\n')
        sorted_counties = sorted(county_index.keys(), key=lambda k: -county_overlap_totals.get(k, 0))
        for i, county_fips in enumerate(sorted_counties):
            bg_ids = county_index[county_fips]
            comma = ',' if i < len(sorted_counties) - 1 else ''
            ids_str = ','.join(f'"{bid}"' for bid in sorted(bg_ids))
            f.write(f'"{county_fips}":[{ids_str}]{comma}\n')
        f.write('};\n')

    file_size = os.path.getsize(OUTPUT_FILE)
    print(f"  Output: {file_size:,} bytes ({file_size/1024:.0f} KB)")

    # Summary stats
    top_counties = sorted(county_overlap_totals.items(), key=lambda x: -x[1])[:10]
    print(f"\nTop 10 overlap counties:")
    for fips, total in top_counties:
        bg_count = len(county_index[fips])
        print(f"  {fips}: {total:>8,} overlap BSLs across {bg_count:>4} block groups")

    print(f"\nDone. Include in dashboard with: <script src=\"overlap_bg_data.js\"></script>")


if __name__ == '__main__':
    main()
